version: '3'

services:
  db:
    container_name: db
    image: postgres:13.2
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_app

  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    command: go run main.go
    volumes:
      - ../:/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
